#!/bin/sh
set -e

echo ">> Waiting minio start..."
sleep 5

mc alias set local http://minio:9000 admin admin123

# create bucket
mc mb --ignore-existing local/files

# Create user AccessKey/SecretKey static
mc admin user add local EVarWQp0g0Vf12VwKAH7 LmQg7mEsgmAU5tEi6ktqlLrbcnuK1VQod6R3jQJa

# Grant full access
mc admin policy attach local readwrite --user=EVarWQp0g0Vf12VwKAH7

echo ">> Create bucket success!"
